@gumtree
Feature: Create API Tests

  @test
  Scenario: GET and POST call to fake API and validate the responses
    Given I create a random userId
    And I set the GET api URL
    When I make a GET request to api
    Then status code should be 200
    And response should contain newly generated id
    And id in the the response should be between 1 and 100
    Given I add the body for POST call
    And I set the POST api URL
    When I make a POST request to api
    Then status code should be 201
    And response should contain below items:
      | userID             | title     | body     |
      | autoGeneratedValue | TestTitle | TestBody |
